name: stale

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  mark-stale:
    uses: cisco-ospo/.github/.github/workflows/_stale.yml@main
    permissions:
      issues: write
      pull-requests: write
    with:
      days-until-stale: 1
      days-until-close: 2
