name: stale

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  stale:
    uses: cisco-ospo/.github/.github/workflows/stale.yml@main
    permissions:
      issues: write
      pull-requests: write
    with:
      days-before-stale: 2
      days-before-close: 7
