name: stale

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: cisco-ospo/.github/.github/workflows/stale.yml@main
    with:
      days-before-stale: 2
      days-before-close: 7
