name: stale

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mark-stale:
    # Call reusable workflow file
    uses: cisco-ospo/.github/.github/workflows/_stale.yml@main
    permissions:
      issues: write
      pull-requests: write
    with:
      days-until-stale: 60
      days-until-close: 7
